[features]
seeds = false
skip-lint = false
[programs.localnet]
liquidity_pools = "DEWi9FJQE9tjqvTxPtLiEQ9yyHT7JnR5FXLA3GMpx3Np"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nikolaycholakov/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
